### ISSUE TITLE
Trainings

### ISSUE THREAD

**Issue by suprenant** [18F/agile#71]
What we're after:
(who are users?) 
(what is demand?)

Guild develop content to help deliver training
Point training materials back to Agile Guild materials
These developed outside of the guild originally
Check in, see if they’d like to tie some of what they present back

Things we can try: 
 - [ ] Probe more at demand, send Slack poll (capabilities, trainings)
 - [ ] Review what else we've done (Agile Corps, DigitalGov)
 - [ ] Recordings of Agile 101, Agile 102 (Alan A., Alan B.)

**Comment by porta-antiporta** [comment]
Will be discussing at 8/10 guild meeting:
- What's available, how the demand has been
- What's effective "training"?
- What are some topics guild could develop content for?

**Comment by porta-antiporta** [comment]
Other food for thought:

> In general, I think we need more avenues for open-ended discussion of all aspects of Agile. scaling is just one of them. I wish we had an open, internal blog to address these things but that was deemed too... something... when I proposed it a couple of years ago.

**Comment by porta-antiporta** [comment]
Notes 8/10

- Scenario based training (couple of examples)
-- Whoever is attending you'll be able to participate more rather than just listening to the instructor.
-- Take a scenario
-- SAFe material takes a similar approach of applying concepts to practice.
-- Distributed environment (how to make it work)
    -- Using MURAL
    -- Need people seeing each others' faces
-- See if there's material out there that we could crib
-- Remote vs. post it and markers 
    -- Seeing people's faces
    -- Body language
    -- Table space people are looking at
    -- Brady bunch + Mural
        -- Zoom does breakout rooms
        -- Mural is clunky

-- What has Jez been doing with DevOpsResearchAssociates (DORA).  

- Slides
-- Put out slides with a recording
-- Slideshare - Speaker notes + video
-- Tying it to the way it was delivered (plan in advance how to want it consumed).
-- Next time we have 101 , 102 let's try recording it

Forums?

Is there someone folks can talk to / have coffee about a particular topic - lightweight coaching / office hours.
- 10x interviews
- Agile corps

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
