### ISSUE TITLE
BDD

### ISSUE THREAD

**Issue by suprenant** [18F/agile#72]
_Nice article about coordinating product behavior among cooperating teams with BDD as a building block. One step higher up the abstraction ladder than agreeing on openapi specs!_
https://johnfergusonsmart.com/bdd-treaties/

**Comment by afomi** [comment]
❤️ the idea and effort.

I immediately think of Service Mapping/Blueprinting here, as a high-level perspective, because a Service Map conveys the Use Cases. Can we relate this to Service Design work? Seems _very_ related.

Zooming in a bit, the interaction/UX design, is more product-level behavior... Distilling these patterns and bits into design libraries is good, and it seems to be happening quite a bit 👍

**Comment by afomi** [comment]
@suprenant, any thoughts on what `done` looks like for this Issue? 

I appreciate the concept of being explicit about intended behavior via behavioral (BDD) specifications.

Is there a team or project that would benefit from a BDD Treaty currently or soon? Or... is this already happening somewhere 🤔

**Comment by suprenant** [comment]
Hi, not offhand, but let's pair to refine this the next time we meet!

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.
